### ISSUE TITLE
no author showing up for our spec

### ISSUE THREAD

**Issue by anasereijo** [canonical-web-and-design/specs.canonical.com#70]
Steve and I are both working on a [spec](https://docs.google.com/document/d/1wXB0MKqXxg1Q9geLuaGkfYM2ymp54p7FCbl0RnSlnRU/edit) but our names do not appear on the website. I've heard there's a delay but Steve created the spec yesterday and it still doesn't show up. I also thought it was because our names in the doc appear as chips, but after checking other specs I realised that it should work anyway. Is there anything we can do or is this a bug?

![Screenshot 2022-05-17 at 16.14.09.png](https://images.zenhubusercontent.com/5a9531ab4b5806bc2bc88d30/3f76ed4f-e46b-4de2-b211-0db2533f30ae)

**Comment by anthonydillon** [comment]
Had a quick look into it. This was due to the use of the user tags in the GDoc. This cell needs a string to pull the content through.

**Comment by anthonydillon** [comment]
I have changed it now so should appear shortly.
